force-app/main/default/objects/Response__c/Response__c.object-meta.xml
<CustomObject>
    <description>Adds a feedback on a contact</description>
    <label>Response</label>
    <nameField>
        <label>Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Response__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Responses</relationshipLabel>
    <relationshipName>Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Response__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Template</label>
    <referenceTo>Template__c</referenceTo>
    <relationshipLabel>Responses</relationshipLabel>
    <relationshipName>Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Response_Line_Item__c/Response_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Response Line Item</label>
    <nameField>
        <displayFormat>a-{0000}</displayFormat>
        <label>Response Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Response Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Response_Line_Item__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <referenceTo>Response__c</referenceTo>
    <relationshipLabel>Response Line Items</relationshipLabel>
    <relationshipName>Response_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Response_Line_Item__c/fields/Template_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Template_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Template Line Item</label>
    <referenceTo>Template_Line_Item__c</referenceTo>
    <relationshipLabel>Response Line Items</relationshipLabel>
    <relationshipName>Response_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Response_Line_Item__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Template__c/Template__c.object-meta.xml
<CustomObject>
    <label>Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Template_Line_Item__c/Template_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Template Line Item</label>
    <nameField>
        <label>Template Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Template Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/DisplayFeedbacksOfContactController.cls
public with sharing class DisplayFeedbacksOfContactController {

    @AuraEnabled(cacheable=true)
    public static List<Response__c> getFeedbacks( Id contactId ) {
        return [ SELECT Id, Name, Template__r.Name
                        , ( SELECT Id, Value__c, Template_Line_Item__r.Question__c, Template_Line_Item__r.Name 
                            FROM Response_Line_Items__r ORDER BY Template_Line_Item__r.Name )
                    FROM Response__c 
                    WHERE Contact__c = :contactId ];
    }
}