force-app/main/default/objects/Template__c/Template__c.object-meta.xml
<CustomObject>
    <label>Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Template_Line_Item__c/Template_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Template Line Item</label>
    <nameField>
        <label>Template Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Template Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Template_Line_Item__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>Employee feedback questions asked from customers</description>
    <label>Question</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Template_Line_Item__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <label>Template</label>
    <referenceTo>Template__c</referenceTo>
    <relationshipLabel>Template Line Items</relationshipLabel>
    <relationshipName>Template_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ControllerTemplateLineItem.cls
public  with sharing class ControllerTemplateLineItem {
    @AuraEnabled(cacheable=true)
    public static List<Template_Line_Item__C> getTemplateLineItemList() {
      List<Template_Line_Item__C> tLIList = new List<Template_Line_Item__C>( [ SELECT Id, Name, Template__c, Question__c
                                                                              FROM Template_Line_Item__C ] );
        return tLIList;
    }
}